version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ramari-postgres
      POSTGRES_PASSWORD: ramari-changeme
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5423:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ramari-pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ramari-admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: